# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily" # Check for updates daily
      pull-request:
        limit: 10 # Limit to 10 open PRs at any time
        labels:
          - "dependencies Update" # Apply labels to PRs for easier discovery
