name: Registry Publish
# This workflow publishes the package to both NPM and GitHub Package Registries
on:
    push:
        branches:
            - main

jobs:
    publish_to_npm:
        name: Publish to NPM Registry
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: yarn install
            - name: Run Tests
              run: yarn test
            - name: Build Package
              run: yarn run build
            - name: Set NPM Auth Token
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
            - name: Publish to NPM
              run: npm publish --registry https://registry.npmjs.org --access public

    publish_to_github:
        name: Publish to GitHub Registry
        runs-on: ubuntu-latest
        needs: publish_to_npm
        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: yarn install
            - name: Run Tests
              run: yarn test
            - name: Build Package
              run: yarn run build
            - name: Set GitHub Auth Token
              run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_AUTH_TOKEN }}" >> ~/.npmrc
            - name: Change Package Name
              run: |
                  sed -i "2s/\"mongosuper\"/\"@${{ secrets.GIT_USER_NAME }}\/mongosuper\"/" package.json
            - name: Publish to GitHub Packages
              run: npm publish --registry=https://npm.pkg.github.com --scope=@${{ secrets.GIT_USER_NAME }} --access public
